### test welcome message localhost
GET http://localhost:8080/boats/api/boat

### test welcome message deployed
GET https://dengamlegymnastiksal.dk/tomcat/boats/api/boat

### get owners from localhost
GET http://localhost:8080/boats/api/boat/owner

### get owners from deployed
GET https://dengamlegymnastiksal.dk/tomcat/boats/api/owner

###
GET http://localhost:8080/boats/api/boat/populate
